/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ui;
import Jeu.*;
import java.util.ArrayList;
/**
 *
 * @author gueganb
 */
public class EchangeUI extends javax.swing.JFrame {

    private Joueur j1;
    private Joueur j2;
    private Echange e1;
    private Echange e2;
    private Monopoly monop;
    public EchangeUI() {
        initComponents();
    }
    public EchangeUI(Monopoly monop, Joueur j1, Joueur j2, Echange e1, Echange e2) {
        this.monop=monop;
        this.j1=j1;
        this.j2=j2;
        this.e2=e2;
        this.e1=e1;
        initComponents();
        setValues();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom1 = new java.awt.Label();
        nom2 = new java.awt.Label();
        labelArgent1 = new java.awt.Label();
        labelArgDispo1 = new java.awt.Label();
        labelArgent2 = new java.awt.Label();
        labelArgDispo2 = new java.awt.Label();
        accepter = new javax.swing.JButton();
        refuser = new javax.swing.JButton();
        ajouter1 = new javax.swing.JButton();
        supprimer1 = new javax.swing.JButton();
        ajouter2 = new javax.swing.JButton();
        supprimer2 = new javax.swing.JButton();
        listProp1 = new java.awt.List();
        listProp2 = new java.awt.List();
        labelArgent = new java.awt.TextField();
        labelArgentb = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nom1.setAlignment(java.awt.Label.CENTER);
        nom1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        nom2.setAlignment(java.awt.Label.CENTER);
        nom2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        labelArgent1.setText("Argent ajouté :");

        labelArgDispo1.setText("Argent disponible :");

        labelArgent2.setText("Argent ajouté :");

        labelArgDispo2.setText("Argent disponible :");

        accepter.setText("Accepter");
        accepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepterActionPerformed(evt);
            }
        });

        refuser.setText("Refuser");
        refuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refuserActionPerformed(evt);
            }
        });

        ajouter1.setText("Ajouter");
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });

        supprimer1.setText("Supprimer");
        supprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer1ActionPerformed(evt);
            }
        });

        ajouter2.setText("Ajouter");
        ajouter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter2ActionPerformed(evt);
            }
        });

        supprimer2.setText("Supprimer");
        supprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer2ActionPerformed(evt);
            }
        });

        labelArgent.setEditable(false);
        labelArgent.setText("0");
        labelArgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelArgentMouseClicked(evt);
            }
        });

        labelArgentb.setEditable(false);
        labelArgentb.setText("0");
        labelArgentb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelArgentbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelArgDispo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelArgent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(labelArgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(listProp1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(nom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(supprimer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ajouter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(supprimer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ajouter2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelArgent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelArgentb, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addComponent(labelArgDispo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listProp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(accepter)
                .addGap(73, 73, 73)
                .addComponent(refuser, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listProp1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nom2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listProp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(ajouter1)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ajouter2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supprimer2)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelArgent2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelArgent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelArgent1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(labelArgentb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelArgDispo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelArgDispo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accepter)
                    .addComponent(refuser))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        nom1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed
        if (ajouter1.isEnabled()){
            if(!(j1.listeProprietesEchangeables().isEmpty())){
            CarreauPropriete cp1 =BoiteDialogUI.ajouterPropriete(this, "Ajouter une propriété", j1.listeProprietesEchangeables());
            e1.addP(cp1);
            setListProp1();
            }
        }
    }//GEN-LAST:event_ajouter1ActionPerformed

    private void ajouter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter2ActionPerformed
        if (ajouter2.isEnabled()){
           if(!(j2.listeProprietesEchangeables().isEmpty())){
            e2.addP(BoiteDialogUI.ajouterPropriete(this, "Ajouter une propriété", j2.listeProprietesEchangeables()));
            setListProp2();
           }
        }
    }//GEN-LAST:event_ajouter2ActionPerformed

    private void supprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer1ActionPerformed
        if (supprimer1.isEnabled()){
            CarreauPropriete cp1 = null;
            for (CarreauPropriete cp : e1.getListP()){
                if (cp.getNom().equals(listProp1.getSelectedItem())){
                    cp1=cp;
                }
            }
            e1.getListP().remove(cp1);
        }
        setListProp2();
    }//GEN-LAST:event_supprimer1ActionPerformed

    private void supprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer2ActionPerformed
        if (supprimer2.isEnabled()){
            CarreauPropriete cp1 = null;
            for (CarreauPropriete cp : e2.getListP()){
                if (cp.getNom().equals(listProp2.getSelectedItem())){
                    cp1=cp;
                }
            }
            e2.getListP().remove(cp1);
        }
        setListProp2();
    }//GEN-LAST:event_supprimer2ActionPerformed

    private void accepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepterActionPerformed
        if (accepter.isEnabled()){
            monop.echanger(j1, j2, e1, e2);
            this.setVisible(false);
        }
    }//GEN-LAST:event_accepterActionPerformed

    private void labelArgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelArgentMouseClicked
      
            e1.setSomme(BoiteDialogUI.choixSomme(this, "Choisissez une somme"));
            setValues();
        
    }//GEN-LAST:event_labelArgentMouseClicked

    private void labelArgentbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelArgentbMouseClicked
        e2.setSomme(BoiteDialogUI.choixSomme(this, "Choisissez une somme"));
        setValues();
        
    }//GEN-LAST:event_labelArgentbMouseClicked

    private void refuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refuserActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_refuserActionPerformed
    
    
    
    
    
    
    public void setListProp1(){
        listProp1.clear();
        for (CarreauPropriete cp : e1.getListP()){
            listProp1.add(cp.getNom());
        }
    }
    public void setListProp2(){
        listProp2.clear();
        for (CarreauPropriete cp : e2.getListP()){
            listProp2.add(cp.getNom());
        }
    }
    public void setValues (){
      nom1.setText(j1.getNomJoueur());
      nom2.setText(j2.getNomJoueur());
      labelArgDispo1.setText("Argent disponible :"+(j1.getCash()-e1.getSomme()));
      labelArgDispo2.setText("Argent disponible :"+(j2.getCash()-e2.getSomme()));
      labelArgent.setText(String.valueOf(e1.getSomme()));
      labelArgentb.setText(String.valueOf(e2.getSomme()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EchangeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EchangeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EchangeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EchangeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EchangeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepter;
    private javax.swing.JButton ajouter1;
    private javax.swing.JButton ajouter2;
    private java.awt.Label labelArgDispo1;
    private java.awt.Label labelArgDispo2;
    private java.awt.TextField labelArgent;
    private java.awt.Label labelArgent1;
    private java.awt.Label labelArgent2;
    private java.awt.TextField labelArgentb;
    private java.awt.List listProp1;
    private java.awt.List listProp2;
    private java.awt.Label nom1;
    private java.awt.Label nom2;
    private javax.swing.JButton refuser;
    private javax.swing.JButton supprimer1;
    private javax.swing.JButton supprimer2;
    // End of variables declaration//GEN-END:variables
}
