/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ui;

import Jeu.*;
import java.awt.TextArea;

/**
 *
 * @author gueganb
 */
public class Plateau extends javax.swing.JFrame {
        private Monopoly monop;
        private PlateauUI plateauUI;
    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
    }
    
    public Plateau (Monopoly monop){
        this.monop=monop;
        initComponents();
        initComponentsUI();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomJLabel = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        lancerDes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        echanger = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cashLabel = new java.awt.Label();
        enTauleLabel = new java.awt.Label();
        cartePrisonLabel = new javax.swing.JLabel();
        desk = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        nomJLabel.setAlignment(java.awt.Label.CENTER);
        nomJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nomJLabel.setText("NomJoueur à toi de jouer !");

        lancerDes.setText("Lancer les dés");
        lancerDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancerDesActionPerformed(evt);
            }
        });

        jButton2.setText("Construire");

        echanger.setText("Echanger");
        echanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                echangerActionPerformed(evt);
            }
        });

        jButton5.setText("Hypothéquer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cashLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        enTauleLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        cartePrisonLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enTauleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lancerDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(echanger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cartePrisonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(nomJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lancerDes)
                    .addComponent(jButton5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(echanger))
                .addGap(74, 74, 74)
                .addComponent(cashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(enTauleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartePrisonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cashLabel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void initComponentsUI() {
        plateauUI = new PlateauUI(monop);
        desk.add(plateauUI);
    }
    
    public void setValues(Joueur j) {
        if (j.getPrison()) {
            enTauleLabel.setText("En prison : oui");
        } else {
            enTauleLabel.setText("En prison : non");
        }
        cashLabel.setText("Argent : " + j.getCash() + "€");
        cartePrisonLabel.setText("Nombre de carte sortie de prison : " + j.getNBCartePrison());
        nomJLabel.setText(j.getNomJoueur()+" à toi de jouer !");
    }
    
    public void update() {
        plateauUI.update();
    }
    
    private void lancerDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancerDesActionPerformed
        if (lancerDes.isEnabled()){
            monop.lancerDes(0); 
        }
    }//GEN-LAST:event_lancerDesActionPerformed

    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void echangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_echangerActionPerformed
        if (echanger.isEnabled()){
            Joueur j1 = monop.getjTemp();
            Joueur j2 = BoiteDialogUI.choixJoueur(this, "Choisir un joueur", monop);
            Echange e1 = new Echange (j1);
            Echange e2 = new Echange (j2);
            EchangeUI eUi = new EchangeUI(monop, j1, j2, e1, e2);
            eUi.setVisible(true);
        }
    }//GEN-LAST:event_echangerActionPerformed

    public void messageLog (String s){
       textArea1.setEditable(false);
       textArea1.append(retourALaLigne(s,55)+"\n");
    
    }
    
    private String retourALaLigne(String s,int longueurLigne) {
        String reponse = "";
        int size = 0;
        String[] tableau = s.split(" ");
        for (String mot : tableau) {
            size+=mot.length()+1;
            if (size>longueurLigne) {
                 reponse = reponse + "\n";
                size=0;
            }
            reponse = reponse + mot + " ";
        }
        return reponse;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plateau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartePrisonLabel;
    private java.awt.Label cashLabel;
    private javax.swing.JPanel desk;
    private javax.swing.JButton echanger;
    private java.awt.Label enTauleLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton lancerDes;
    private java.awt.Label nomJLabel;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
